### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by FlyinP** [Luxadevi/Ollama-Colab-Integration#3] opened 2024-02-10 01:55 UTC
Invalid JSON structure or error in fetching data

**Comment by Luxadevi** [comment] 2024-02-10 09:34
No models found or loaded.
Try downloading a model from the modelfile creator.

**Comment by FlyinP** [comment] 2024-02-16 06:48
said 
```
Status Legend:
(OK):download completed.
```

Is it done? Cant fetch models. no output.

**Comment by Luxadevi** [comment] 2024-02-21 13:48
I cannot reproduce your issue, do you have some more info?

**Comment by traderpedroso** [comment] 2024-03-02 15:46
Directory not found when using on colab for models from llama.cpp and fetch models not working too

**Comment by Luxadevi** [comment] 2024-05-10 02:35
Llama.cpp doesnt come with models standard,you  have to init them within the app on page "ModelBuilder"
Or download them with the HuggingfaceDownloader page
Other documentation is also available within the app
I will close this issue for now, feel free to reopen whenever you encounter issues.

Gr
Luxa

**Closed as completed by Luxadevi** 2024-05-10 02:35 UTC
